markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title/
auto: true
rdiscount:
  extensions: [smart]

name: Nick Merwin
url: http://nickmerwin.com
description: Coding for kicks.
twitter: nickmerwin
github: nickmerwin
gravatar_url: http://gravatar.com/avatar/4706d1179c3cef5311929b17ef19882a